---
- name: Selenium Automation
  hosts: 172.17.0.2 
  environment:
        http_proxy: http://sumedh_surlekar:Titan1988@hjproxy.persistent.co.in:8080
        https_proxy: https://sumedh_surlekar:Titan1988@hjproxy.persistent.co.in:8080

  tasks:

    - name: Install packages
      script: packages.sh

    - name: Install selenium
      shell: pip install selenium

    - name: Copy test cases file to remote host
      copy: src=test.py dest=/root/
   
    - name: Copy test cases file to remote host
      copy: src=testreport.sh dest=/root/ mode=0744

    - name: Analyse test result
      shell: ./testreport.sh '{{ vmIP }}' '{{ port }}' '{{ buildno }}'
