---
- name: Selenium Automation
  hosts: "{{ host }}"
  environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"

  tasks:

    - name: Install Packages
      apt: name= {{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
      with_items:
        - firefox 
        - xvfb 
        - python-pip 
        - subversion
    
    - name: Install selenium
      shell: pip install selenium

    - name: Copy test cases file to remote host
      copy: src=test.py dest=/root/


    - name: Analyse test result
      script: testreport.sh
