---
- name: Selenium Automation
  hosts: '{{ host }}' 
  environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"

  tasks:

    - name: Install packages
      script: packages.sh

    - name: Install selenium
      shell: pip install selenium

    - name: Copy test cases file to remote host
      copy: src=test.py dest=/root/
   
    - name: Copy test cases file to remote host
      copy: src=testreport.sh dest=/root/ mode=0744

    - name: Analyse test result
      shell: ./testreport.sh '{{ vmIP }}' '{{ port }}' '{{ buildno }}'
