---
- name: Selenium Automation
  hosts: '{{ host }}' 
  environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}" 

  tasks:

    - name: Install packages
      script: packages.sh

    - name: Install selenium
      shell: pip install selenium

    - name: Copy test cases file to remote host
      copy: src=test.py dest=/root/


    - name: Analyse test result
      script: testreport.sh
